### ISSUE TITLE
Filename completions

### ISSUE THREAD

**Issue by zzamboni** [dcu/elvish-completer-generator#1]
First of all - awesome work! This is a great starting point and will enable the creation of a much larger library of Elvish completions.

One obvious addition would be to automate the completion of filenames in commands. I haven't looked at the code too much so I don't really know how hard it will be, but one idea would be to look for UPPERCASE parts in the command synopsis. For example, `man cp` shows:

```
       cp [OPTION]... [-T] SOURCE DEST
       cp [OPTION]... SOURCE... DIRECTORY
       cp [OPTION]... -t DIRECTORY SOURCE...
```

There are many many variations of these patterns, so I'm not sure if this can be reliably achieved :(

**Comment by dcu** [comment]
I added support for matching file names in the latest commit
